### ISSUE TITLE
[叨扰]

### ISSUE THREAD

**Issue by alaskasquirrel** [geekplux/site#3]
由于本人没有大众社交帐号，故在此打扰。在你的博客推荐中看到不少有趣的分享。本人创建搜集的[Chinese-Podcasts](https://github.com/alaskasquirrel/Chinese-Podcasts)&[Email-newsletter-RSS](https://github.com/alaskasquirrel/Email-newsletter-RSS) 期待你的参与。(这两个项目日常都是本人更新，日趋单调)

**Comment by geekplux** [comment]
做的很棒！感觉已经很全了
